# Generated by Django 5.2.6 on 2025-11-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkashiOrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='No')),
                ('data_classification', models.CharField(blank=True, max_length=10, null=True, verbose_name='データ区分')),
                ('order_classification', models.IntegerField(blank=True, null=True, verbose_name='発注区分')),
                ('delivery_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='納番')),
                ('acceptance', models.IntegerField(blank=True, null=True, verbose_name='受入')),
                ('jersey_number', models.IntegerField(blank=True, null=True, verbose_name='背番号')),
                ('product_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='品番')),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='納入日')),
                ('flight', models.IntegerField(blank=True, null=True, verbose_name='便')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='収容数')),
                ('box_quantity', models.IntegerField(blank=True, null=True, verbose_name='箱数')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '明石発注データリスト',
                'verbose_name_plural': '明石発注データリスト',
                'ordering': ['-delivery_date', 'flight', 'no'],
                'indexes': [models.Index(fields=['product_number', 'delivery_date'], name='management__product_f18720_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='部署名')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='部署コード')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='management_room.department', verbose_name='親部署')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
                'ordering': ['-active', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(db_index=True, max_length=100, verbose_name='従業員番号')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='内線番号')),
                ('card_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='カードNo')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('in_room', models.BooleanField(default=False, verbose_name='在籍管理')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.line', verbose_name='ライン')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='異動日')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='部署離脱日')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employee', to='management_room.department', verbose_name='部署')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employee', to='management_room.employee', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '部署所属履歴',
                'verbose_name_plural': '部署所属履歴',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='management_room.employee', verbose_name='部署長'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['active', 'name'], name='management__active_b8ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['active', 'code'], name='management__active_eeba77_idx'),
        ),
    ]
