# Generated by Django 5.2.6 on 2025-11-10 17:47

import daihatsu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='完成品番')),
                ('is_oneline_only', models.BooleanField(default=True, verbose_name='1ライン専用')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '完成品番',
                'verbose_name_plural': '完成品番',
                'ordering': ['-active', 'name'],
                'indexes': [models.Index(fields=['active', 'name'], name='management__active_7c319d_idx')],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
    ]
