# Generated by Django 5.2.6 on 2025-11-11 08:09

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0002_assemblyitem'),
        ('manufacturing', '0006_machine_alter_machiningmachine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('tact', models.FloatField(blank=True, default=0, null=True, verbose_name='タクト')),
                ('good_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='良品率')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingmachine', verbose_name='鋳造機')),
            ],
            options={
                'verbose_name': '鋳造品番',
                'verbose_name_plural': '鋳造品番',
                'ordering': ['-active', 'line', 'machine', 'name'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DailyCastingProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('holding_out_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち出し数')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.castingitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別鋳造計画',
                'verbose_name_plural': '日別鋳造計画',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMachineCastingProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('production_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産数')),
                ('stop_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='計画停止')),
                ('overtime', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_casting_production_plans', to='manufacturing.castingline', verbose_name='鋳造ライン')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_casting_production_plans', to='manufacturing.castingmachine', verbose_name='鋳造機')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.castingitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別鋳造計画品番',
                'verbose_name_plural': '日別鋳造計画品番',
                'ordering': ['-date', 'shift', 'machine', 'production_item'],
            },
        ),
        migrations.AddIndex(
            model_name='castingitem',
            index=models.Index(fields=['line', 'machine', 'active', 'name'], name='management__line_id_f772dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycastingproductionplan',
            index=models.Index(fields=['line', 'date', 'shift'], name='management__line_id_9e2caf_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycastingproductionplan',
            index=models.Index(fields=['line', 'date', 'shift', 'production_item'], name='management__line_id_206c96_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymachinecastingproductionplan',
            index=models.Index(fields=['date', 'shift', 'machine', 'production_item'], name='management__date_c98213_idx'),
        ),
    ]
