# Generated by Django 5.2.6 on 2025-11-11 09:15

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0003_castingitem_dailycastingproductionplan_and_more'),
        ('manufacturing', '0006_machine_alter_machiningmachine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachiningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('tact', models.FloatField(blank=True, default=0, null=True, verbose_name='タクト')),
                ('good_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='良品率')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.machiningline', verbose_name='加工ライン')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.machiningmachine', verbose_name='加工機')),
            ],
            options={
                'verbose_name': '鋳造品番',
                'verbose_name_plural': '鋳造品番',
                'ordering': ['-active', 'line', 'machine', 'name'],
                'indexes': [models.Index(fields=['line', 'machine', 'active', 'name'], name='management__line_id_56fcae_idx')],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
    ]
