# Generated by Django 5.2.6 on 2025-11-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0004_machiningitem'),
        ('manufacturing', '0007_remove_line_yield_rate_assemblyline_tact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castingitem',
            old_name='good_rate',
            new_name='yield_rate',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='is_oneline_only',
        ),
        migrations.RemoveField(
            model_name='machiningitem',
            name='good_rate',
        ),
        migrations.RemoveField(
            model_name='machiningitem',
            name='tact',
        ),
        migrations.AddField(
            model_name='assemblyitem',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.assemblyline', verbose_name='組立ライン'),
        ),
    ]
