# Generated by Django 5.2.6 on 2025-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0005_rename_good_rate_castingitem_yield_rate_and_more'),
        ('manufacturing', '0007_remove_line_yield_rate_assemblyline_tact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machiningitem',
            options={'ordering': ['-active', 'line', 'name'], 'verbose_name': '加工品番', 'verbose_name_plural': '加工品番'},
        ),
        migrations.RemoveIndex(
            model_name='machiningitem',
            name='management__line_id_56fcae_idx',
        ),
        migrations.RemoveField(
            model_name='machiningitem',
            name='machine',
        ),
        migrations.AddIndex(
            model_name='machiningitem',
            index=models.Index(fields=['line', 'active', 'name'], name='management__line_id_11e98d_idx'),
        ),
    ]
