# Generated by Django 5.2.6 on 2025-11-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0006_alter_machiningitem_options_and_more'),
        ('manufacturing', '0008_machiningline_assembly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyitem',
            options={'ordering': ['-active', 'line', 'name'], 'verbose_name': '完成品番', 'verbose_name_plural': '完成品番'},
        ),
        migrations.CreateModel(
            name='DailyAssenblyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('holding_out_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.castingitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別組付生産計画',
                'verbose_name_plural': '日別組付生産計画',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['line', 'date', 'shift'], name='management__line_id_d119a4_idx'), models.Index(fields=['line', 'date', 'shift', 'production_item'], name='management__line_id_0d4da0_idx')],
            },
        ),
    ]
