# Generated by Django 5.2.6 on 2025-11-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0007_alter_assemblyitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyItemMachiningItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('assembly_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_item_machining_items', to='management_room.assemblyitem', verbose_name='完成品番')),
                ('machining_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_item_machining_items', to='management_room.machiningitem', verbose_name='加工品番')),
            ],
            options={
                'verbose_name': '完成品番-加工品番紐付け',
                'verbose_name_plural': '完成品番-加工品番紐付け',
                'ordering': ['assembly_item', 'machining_item'],
                'indexes': [models.Index(fields=['assembly_item', 'machining_item'], name='management__assembl_5b2c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachiningItemCastingItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('casting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machining_item_casting_items', to='management_room.castingitem', verbose_name='鋳造品番')),
                ('machining_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machining_item_casting_items', to='management_room.machiningitem', verbose_name='加工品番')),
            ],
            options={
                'verbose_name': '加工品番-鋳造品番紐付け',
                'verbose_name_plural': '加工品番-鋳造品番紐付け',
                'ordering': ['machining_item', 'casting_item'],
                'indexes': [models.Index(fields=['machining_item', 'casting_item'], name='management__machini_73eb14_idx')],
            },
        ),
    ]
