# Generated by Django 5.2.6 on 2025-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0008_assemblyitemmachiningitemmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyitemmachiningitemmap',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AddField(
            model_name='machiningitemcastingitemmap',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
    ]
