# Generated by Django 5.2.6 on 2025-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0009_assemblyitemmachiningitemmap_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyitem',
            name='main_line',
            field=models.BooleanField(default=False, verbose_name='メインライン'),
        ),
    ]
