# Generated by Django 5.2.6 on 2025-11-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0010_assemblyitem_main_line'),
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyassenblyproductionplan',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.assemblyline', verbose_name='組付ライン'),
        ),
        migrations.AlterField(
            model_name='dailyassenblyproductionplan',
            name='production_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.assemblyitem', verbose_name='品番'),
        ),
    ]
