# Generated by Django 5.2.6 on 2025-11-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0011_alter_dailyassenblyproductionplan_line_and_more'),
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAssemblyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, db_index=True, null=True, verbose_name='月')),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.assemblyline', verbose_name='組付ライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.assemblyitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '月別組付生産計画',
                'verbose_name_plural': '月別組付生産計画',
                'ordering': ['-month', 'line'],
                'indexes': [models.Index(fields=['line', 'month'], name='management__line_id_f43b7f_idx'), models.Index(fields=['line', 'month', 'production_item'], name='management__line_id_9ca761_idx')],
            },
        ),
    ]
