# Generated by Django 5.2.6 on 2025-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0012_monthlyassemblyproductionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyassenblyproductionplan',
            old_name='holding_out_count',
            new_name='production_quantity',
        ),
        migrations.AddField(
            model_name='dailyassenblyproductionplan',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業数'),
        ),
        migrations.AddField(
            model_name='dailyassenblyproductionplan',
            name='stop_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='計画停止'),
        ),
    ]
