# Generated by Django 5.2.6 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0013_rename_holding_out_count_dailyassenblyproductionplan_production_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassenblyproductionplan',
            name='occupancy_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='稼働率'),
        ),
    ]
