# Generated by Django 5.2.6 on 2025-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0014_dailyassenblyproductionplan_occupancy_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassenblyproductionplan',
            name='holding_out_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち出し数'),
        ),
    ]
