# Generated by Django 5.2.6 on 2025-11-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0015_dailyassenblyproductionplan_holding_out_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyassenblyproductionplan',
            name='holding_out_count',
        ),
    ]
