# Generated by Django 5.2.6 on 2025-11-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0016_remove_dailyassenblyproductionplan_holding_out_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyassemblyproductionplan',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
