# Generated by Django 5.2.6 on 2025-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0017_rename_quantity_monthlyassemblyproductionplan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassenblyproductionplan',
            name='regular_working_hours',
            field=models.BooleanField(default=True, verbose_name='定時'),
        ),
    ]
