# Generated by Django 5.2.6 on 2025-11-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0018_dailyassenblyproductionplan_regular_working_hours'),
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMachiningProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('production_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産数')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫数')),
                ('shipment', models.IntegerField(blank=True, default=0, null=True, verbose_name='出荷数')),
                ('stop_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='計画停止')),
                ('overtime', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業数')),
                ('occupancy_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='稼働率')),
                ('regular_working_hours', models.BooleanField(default=True, verbose_name='定時')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.machiningline', verbose_name='加工ライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.machiningitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別加工生産計画',
                'verbose_name_plural': '日別加工生産計画',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['line', 'date', 'shift'], name='management__line_id_2567e4_idx'), models.Index(fields=['line', 'date', 'shift', 'production_item'], name='management__line_id_faf8d9_idx')],
            },
        ),
    ]
