# Generated by Django 5.2.6 on 2025-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0019_dailymachiningproductionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='castingitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='machiningitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順'),
        ),
    ]
