# Generated by Django 5.2.6 on 2025-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0020_assemblyitem_order_castingitem_order_and_more'),
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyitem',
            options={'ordering': ['-active', 'line', 'order'], 'verbose_name': '完成品番', 'verbose_name_plural': '完成品番'},
        ),
        migrations.AlterModelOptions(
            name='castingitem',
            options={'ordering': ['-active', 'line', 'machine', 'order'], 'verbose_name': '鋳造品番', 'verbose_name_plural': '鋳造品番'},
        ),
        migrations.RemoveIndex(
            model_name='machiningitem',
            name='management__line_id_11e98d_idx',
        ),
        migrations.AddField(
            model_name='machiningitem',
            name='main_line',
            field=models.BooleanField(default=False, verbose_name='メインライン'),
        ),
        migrations.AddIndex(
            model_name='machiningitem',
            index=models.Index(fields=['line', 'active', 'order'], name='management__line_id_7c6746_idx'),
        ),
    ]
