# Generated by Django 5.2.6 on 2025-11-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0021_alter_assemblyitem_options_alter_castingitem_options_and_more'),
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machiningitem',
            options={'ordering': ['-active', 'assembly_line', 'line', 'name'], 'verbose_name': '加工品番', 'verbose_name_plural': '加工品番'},
        ),
        migrations.AddField(
            model_name='machiningitem',
            name='assembly_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.assemblyline', verbose_name='組付ライン'),
        ),
    ]
