# Generated by Django 5.2.6 on 2025-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0022_alter_machiningitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymachiningproductionplan',
            name='stock',
        ),
        migrations.CreateModel(
            name='MachiningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ライン名')),
                ('item_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='品番名')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '加工在庫',
                'verbose_name_plural': '加工在庫',
                'ordering': ['-date', 'shift'],
                'indexes': [models.Index(fields=['line_name', 'date', 'shift'], name='management__line_na_dbba0d_idx'), models.Index(fields=['line_name', 'date', 'shift', 'item_name'], name='management__line_na_bc36ee_idx')],
            },
        ),
    ]
