# Generated by Django 5.2.6 on 2025-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0023_remove_dailymachiningproductionplan_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machiningitem',
            name='optimal_inventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最適在庫数'),
        ),
    ]
