# Generated by Django 5.2.6 on 2025-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0024_machiningitem_optimal_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingitem',
            name='optimal_inventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='適正在庫数'),
        ),
        migrations.AlterField(
            model_name='machiningitem',
            name='optimal_inventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='適正在庫数'),
        ),
    ]
