# Generated by Django 5.2.6 on 2025-11-17 17:54

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0025_castingitem_optimal_inventory_and_more'),
        ('manufacturing', '0010_alter_line_options_alter_machine_options_line_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingItemMachineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tact', models.FloatField(blank=True, default=0, null=True, verbose_name='タクト')),
                ('yield_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='良品率')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '鋳造品番',
                'verbose_name_plural': '鋳造品番',
                'ordering': ['-active', 'line', 'machine', 'order'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='castingitem',
            options={'ordering': ['-active', 'line', 'order'], 'verbose_name': '鋳造品番', 'verbose_name_plural': '鋳造品番'},
        ),
        migrations.RemoveIndex(
            model_name='castingitem',
            name='management__line_id_f772dc_idx',
        ),
        migrations.RemoveField(
            model_name='castingitem',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='castingitem',
            name='tact',
        ),
        migrations.RemoveField(
            model_name='castingitem',
            name='yield_rate',
        ),
        migrations.AddIndex(
            model_name='castingitem',
            index=models.Index(fields=['line', 'active', 'name'], name='management__line_id_dcb9d8_idx'),
        ),
        migrations.AddField(
            model_name='castingitemmachinemap',
            name='casting_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.castingitem', verbose_name='鋳造品番'),
        ),
        migrations.AddField(
            model_name='castingitemmachinemap',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン'),
        ),
        migrations.AddField(
            model_name='castingitemmachinemap',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingmachine', verbose_name='鋳造機'),
        ),
        migrations.AddIndex(
            model_name='castingitemmachinemap',
            index=models.Index(fields=['line', 'machine', 'active', 'casting_item'], name='management__line_id_056706_idx'),
        ),
    ]
