# Generated by Django 5.2.6 on 2025-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0026_castingitemmachinemap_alter_castingitem_options_and_more'),
        ('manufacturing', '0010_alter_line_options_alter_machine_options_line_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingitemmachinemap',
            options={'ordering': ['-active', 'line__order', 'machine__order', 'casting_item__order'], 'verbose_name': '鋳造品番-設備紐づけ', 'verbose_name_plural': '鋳造品番-設備紐づけ'},
        ),
        migrations.RemoveIndex(
            model_name='castingitemmachinemap',
            name='management__line_id_056706_idx',
        ),
        migrations.RemoveField(
            model_name='castingitemmachinemap',
            name='order',
        ),
        migrations.AddIndex(
            model_name='castingitemmachinemap',
            index=models.Index(fields=['line', 'machine', 'casting_item', 'active'], name='management__line_id_3e1942_idx'),
        ),
    ]
