# Generated by Django 5.2.6 on 2025-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0027_alter_castingitemmachinemap_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machiningitemcastingitemmap',
            options={'ordering': ['machining_line_name', 'machining_item_name', 'casting_line_name', 'casting_item_name'], 'verbose_name': '加工品番-鋳造品番紐付け', 'verbose_name_plural': '加工品番-鋳造品番紐付け'},
        ),
        migrations.RemoveIndex(
            model_name='machiningitemcastingitemmap',
            name='management__machini_73eb14_idx',
        ),
        migrations.RemoveField(
            model_name='machiningitemcastingitemmap',
            name='casting_item',
        ),
        migrations.RemoveField(
            model_name='machiningitemcastingitemmap',
            name='machining_item',
        ),
        migrations.AddField(
            model_name='machiningitemcastingitemmap',
            name='casting_item_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='鋳造品番名'),
        ),
        migrations.AddField(
            model_name='machiningitemcastingitemmap',
            name='casting_line_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='鋳造ライン名'),
        ),
        migrations.AddField(
            model_name='machiningitemcastingitemmap',
            name='machining_item_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='加工品番名'),
        ),
        migrations.AddField(
            model_name='machiningitemcastingitemmap',
            name='machining_line_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='加工ライン名'),
        ),
        migrations.AddIndex(
            model_name='machiningitemcastingitemmap',
            index=models.Index(fields=['machining_line_name', 'machining_item_name', 'casting_line_name', 'casting_item_name'], name='management__machini_227bf0_idx'),
        ),
    ]
