# Generated by Django 5.2.6 on 2025-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0028_alter_machiningitemcastingitemmap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymachinecastingproductionplan',
            name='mold_change',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='金型交換'),
        ),
        migrations.AlterField(
            model_name='dailyassenblyproductionplan',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業'),
        ),
        migrations.AlterField(
            model_name='dailymachinecastingproductionplan',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業'),
        ),
        migrations.AlterField(
            model_name='dailymachiningproductionplan',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業'),
        ),
    ]
