# Generated by Django 5.2.6 on 2025-11-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0029_dailymachinecastingproductionplan_mold_change_and_more'),
        ('manufacturing', '0011_castingline_changeover_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingItemProhibitedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True, verbose_name='品番1')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='品番2')),
                ('count', models.IntegerField(blank=True, default=2, null=True, verbose_name='同時生産禁止数')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン')),
            ],
            options={
                'verbose_name': '鋳造同時生産禁止品番パターン',
                'verbose_name_plural': '鋳造同時生産禁止品番パターン',
                'ordering': ['-active', 'line', 'name1', 'name2'],
                'indexes': [models.Index(fields=['line', 'active'], name='management__line_id_659104_idx')],
            },
        ),
    ]
