# Generated by Django 5.2.6 on 2025-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0030_castingitemprohibitedpattern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingitemprohibitedpattern',
            options={'ordering': ['-active', 'line', 'item_name1', 'item_name2'], 'verbose_name': '鋳造同時生産禁止品番パターン', 'verbose_name_plural': '鋳造同時生産禁止品番パターン'},
        ),
        migrations.RenameField(
            model_name='castingitemprohibitedpattern',
            old_name='name1',
            new_name='item_name1',
        ),
        migrations.RenameField(
            model_name='castingitemprohibitedpattern',
            old_name='name2',
            new_name='item_name2',
        ),
    ]
