# Generated by Django 5.2.6 on 2025-11-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0031_alter_castingitemprohibitedpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingitemprohibitedpattern',
            name='item_name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casting_item_prohibited_pattern_item1', to='management_room.castingitem', verbose_name='品番1'),
        ),
        migrations.AlterField(
            model_name='castingitemprohibitedpattern',
            name='item_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casting_item_prohibited_pattern_item2', to='management_room.castingitem', verbose_name='品番2'),
        ),
    ]
