# Generated by Django 5.2.6 on 2025-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0032_alter_castingitemprohibitedpattern_item_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymachinecastingproductionplan',
            name='mold_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='金型使用数'),
        ),
    ]
