# Generated by Django 5.2.6 on 2025-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0034_endofmonthcastingmold'),
        ('manufacturing', '0011_castingline_changeover_time'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='endofmonthcastingmold',
            name='management__line_id_8d8aa2_idx',
        ),
        migrations.AddIndex(
            model_name='endofmonthcastingmold',
            index=models.Index(fields=['line', 'machine', 'date'], name='management__line_id_5d56c1_idx'),
        ),
    ]
