# Generated by Django 5.2.6 on 2025-11-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0035_remove_endofmonthcastingmold_management__line_id_8d8aa2_idx_and_more'),
        ('manufacturing', '0011_castingline_changeover_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsableMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, db_index=True, null=True, verbose_name='月')),
                ('used_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='使用回数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.castingitem', verbose_name='品番')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingline', verbose_name='鋳造ライン')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingmachine', verbose_name='鋳造機')),
            ],
            options={
                'verbose_name': '使用可能金型数',
                'verbose_name_plural': '使用可能金型数',
                'ordering': ['month', 'line', 'machine'],
                'indexes': [models.Index(fields=['line', 'machine'], name='management__line_id_4e2c23_idx')],
            },
        ),
    ]
