# Generated by Django 5.2.6 on 2025-11-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0036_usablemold'),
    ]

    operations = [
        migrations.AddField(
            model_name='usablemold',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='種類'),
        ),
        migrations.DeleteModel(
            name='EndOfMonthCastingMold',
        ),
    ]
