# Generated by Django 5.2.6 on 2025-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0037_usablemold_type_delete_endofmonthcastingmold'),
        ('manufacturing', '0011_castingline_changeover_time'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usablemold',
            name='management__line_id_4e2c23_idx',
        ),
        migrations.RemoveField(
            model_name='usablemold',
            name='type',
        ),
        migrations.AddField(
            model_name='usablemold',
            name='end_of_month',
            field=models.BooleanField(default=False, verbose_name='月末'),
        ),
        migrations.AddIndex(
            model_name='usablemold',
            index=models.Index(fields=['month', 'line', 'machine'], name='management__month_43efbc_idx'),
        ),
    ]
