# Generated by Django 5.2.6 on 2025-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0038_remove_usablemold_management__line_id_4e2c23_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usablemold',
            options={'ordering': ['month', 'line', 'machine'], 'verbose_name': '金型月末、途中交換管理', 'verbose_name_plural': '金型月末、途中交換管理'},
        ),
        migrations.AddField(
            model_name='dailymachinecastingproductionplan',
            name='occupancy_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='稼働率'),
        ),
        migrations.AddField(
            model_name='dailymachinecastingproductionplan',
            name='regular_working_hours',
            field=models.BooleanField(default=True, verbose_name='定時'),
        ),
        migrations.AlterField(
            model_name='castingitemprohibitedpattern',
            name='count',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='同時生産上限'),
        ),
    ]
