# Generated by Django 5.2.6 on 2025-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0039_alter_usablemold_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymachinecastingproductionplan',
            name='regular_working_hours',
            field=models.BooleanField(default=False, verbose_name='定時'),
        ),
    ]
