# Generated by Django 5.2.6 on 2025-11-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0040_alter_dailymachinecastingproductionplan_regular_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingitem',
            name='molten_metal_usage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='溶湯使用量'),
        ),
    ]
