# Generated by Django 5.2.6 on 2025-12-01 14:39

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0041_castingitem_molten_metal_usage'),
        ('manufacturing', '0012_cvtline_cvtmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順')),
                ('optimal_inventory', models.IntegerField(blank=True, default=0, null=True, verbose_name='適正在庫数')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('molten_metal_usage', models.FloatField(blank=True, default=0, null=True, verbose_name='溶湯使用量')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.cvtline', verbose_name='CVTライン')),
            ],
            options={
                'verbose_name': 'CVT品番',
                'verbose_name_plural': 'CVT品番',
                'ordering': ['-active', 'line', 'order'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVTItemMachineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tact', models.FloatField(blank=True, default=0, null=True, verbose_name='タクト')),
                ('yield_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='良品率')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('casting_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.cvtitem', verbose_name='CVT品番')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.cvtline', verbose_name='CVTライン')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.castingmachine', verbose_name='CVT鋳造機')),
            ],
            options={
                'verbose_name': 'CVT品番-設備紐づけ',
                'verbose_name_plural': 'CVT品番-設備紐づけ',
                'ordering': ['-active', 'line__order', 'machine__order', 'casting_item__order'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyCVTProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, db_index=True, null=True, verbose_name='月')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.cvtline', verbose_name='CVTライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.cvtitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '月別CVT生産計画',
                'verbose_name_plural': '月別CVT生産計画',
                'ordering': ['-month', 'line'],
            },
        ),
        migrations.AddIndex(
            model_name='cvtitem',
            index=models.Index(fields=['line', 'active', 'name'], name='management__line_id_f3b7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cvtitemmachinemap',
            index=models.Index(fields=['line', 'machine', 'casting_item', 'active'], name='management__line_id_4b522a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycvtproductionplan',
            index=models.Index(fields=['line', 'month'], name='management__line_id_c6edcc_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycvtproductionplan',
            index=models.Index(fields=['line', 'month', 'production_item'], name='management__line_id_277353_idx'),
        ),
    ]
