# Generated by Django 5.2.6 on 2025-12-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0042_cvtitem_cvtitemmachinemap_monthlycvtproductionplan_and_more'),
        ('manufacturing', '0012_cvtline_cvtmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtitemmachinemap',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.cvtmachine', verbose_name='CVT鋳造機'),
        ),
    ]
