# Generated by Django 5.2.6 on 2025-12-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0043_alter_cvtitemmachinemap_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymachiningproductionplan',
            name='shipment',
        ),
    ]
