# Generated by Django 5.2.6 on 2025-12-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0044_remove_dailymachiningproductionplan_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycastingproductionplan',
            name='holding_out_count',
        ),
    ]
