# Generated by Django 5.2.6 on 2025-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0045_remove_dailycastingproductionplan_holding_out_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyassemblyproductionplan',
            name='tact',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='タクト'),
        ),
    ]
