# Generated by Django 5.2.2 on 2025-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0046_monthlyassemblyproductionplan_tact'),
    ]

    operations = [
        migrations.AddField(
            model_name='machiningstock',
            name='stock_adjustment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫調整数'),
        ),
    ]
