# Generated by Django 5.2.6 on 2025-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0047_machiningstock_stock_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycastingproductionplan',
            name='stock_adjustment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫調整数'),
        ),
    ]
