# Generated by Django 5.2.6 on 2025-12-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0048_dailycastingproductionplan_stock_adjustment'),
        ('manufacturing', '0012_cvtline_cvtmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCVTProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫数')),
                ('stock_adjustment', models.IntegerField(blank=True, default=0, null=True, verbose_name='在庫調整数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.cvtline', verbose_name='CVTライン')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.cvtitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別CVT計画',
                'verbose_name_plural': '日別CVT計画',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['line', 'date', 'shift'], name='management__line_id_beb6bd_idx'), models.Index(fields=['line', 'date', 'shift', 'production_item'], name='management__line_id_0a0d44_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMachineCVTProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('shift', models.CharField(blank=True, max_length=100, null=True, verbose_name='シフト')),
                ('production_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産数')),
                ('mold_change', models.IntegerField(blank=True, default=0, null=True, verbose_name='金型交換')),
                ('stop_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='計画停止')),
                ('overtime', models.IntegerField(blank=True, default=0, null=True, verbose_name='生産残業')),
                ('mold_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='金型使用数')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('occupancy_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='稼働率')),
                ('regular_working_hours', models.BooleanField(default=False, verbose_name='定時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_cvt_production_plans', to='manufacturing.cvtline', verbose_name='CVTライン')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_cvt_production_plans', to='manufacturing.cvtmachine', verbose_name='鋳造機')),
                ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_room.cvtitem', verbose_name='品番')),
            ],
            options={
                'verbose_name': '日別CVT計画品番',
                'verbose_name_plural': '日別CVT計画品番',
                'ordering': ['-date', 'shift', 'machine', 'production_item'],
                'indexes': [models.Index(fields=['date', 'shift', 'machine', 'production_item'], name='management__date_f82d62_idx')],
            },
        ),
    ]
