# Generated by Django 5.2.6 on 2025-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0049_dailycvtproductionplan_dailymachinecvtproductionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='背景色'),
        ),
        migrations.AddField(
            model_name='cvtitem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='背景色'),
        ),
    ]
