# Generated by Django 5.2.6 on 2025-12-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_room', '0050_castingitem_color_cvtitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymachinecvtproductionplan',
            name='mold_count',
        ),
    ]
