# Generated by Django 5.2.6 on 2025-11-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='勤怠日')),
                ('shift_type', models.CharField(choices=[('day', '日勤'), ('night', '夜勤')], default='day', max_length=10, verbose_name='勤務区分')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('own_line_operation_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='自ライン稼働時間')),
                ('production_overtime', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='生産残業時間')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '勤怠記録',
                'verbose_name_plural': '勤怠記録',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='勤怠選択肢')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '勤怠選択',
                'verbose_name_plural': '勤怠選択',
                'ordering': ['-active', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='時間')),
                ('overtime', models.BooleanField(default=False, verbose_name='残業')),
            ],
            options={
                'verbose_name': '応援',
                'verbose_name_plural': '応援',
                'ordering': ['line__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='時間')),
                ('overtime', models.BooleanField(default=False, verbose_name='残業')),
            ],
            options={
                'verbose_name': '業務内容',
                'verbose_name_plural': '業務内容',
                'ordering': ['attendance_select__order', 'attendance_select__name'],
            },
        ),
        migrations.CreateModel(
            name='ActualProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='コード')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '実績生産品目',
                'verbose_name_plural': '実績生産品目',
                'ordering': ['-active', 'code', 'name'],
                'indexes': [models.Index(fields=['active', 'name'], name='actual_prod_active_a69c80_idx'), models.Index(fields=['active', 'code'], name='actual_prod_active_e1b712_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceProductionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
                ('actual_production_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual_production.actualproductionitem', verbose_name='実績生産品目')),
            ],
            options={
                'verbose_name': '勤怠選択肢-実績生産品目紐づけ',
                'verbose_name_plural': '勤怠選択肢-実績生産品目紐づけ',
                'ordering': ['attendance_select__order', 'attendance_select__name', 'actual_production_item__code'],
            },
        ),
    ]
