# Generated by Django 5.2.6 on 2025-11-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actual_production', '0001_initial'),
        ('management_room', '0001_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_room.employee', verbose_name='従業員'),
        ),
        migrations.AddIndex(
            model_name='attendanceselect',
            index=models.Index(fields=['active', 'name'], name='actual_prod_active_cc5190_idx'),
        ),
        migrations.AddField(
            model_name='attendanceproductionmapping',
            name='attendance_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual_production.attendanceselect', verbose_name='勤怠選択肢'),
        ),
        migrations.AddField(
            model_name='attendancesupport',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='actual_production.attendancerecord', verbose_name='勤怠記録'),
        ),
        migrations.AddField(
            model_name='attendancesupport',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.line', verbose_name='応援ライン'),
        ),
        migrations.AddField(
            model_name='attendancetask',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='actual_production.attendancerecord', verbose_name='勤怠記録'),
        ),
        migrations.AddField(
            model_name='attendancetask',
            name='attendance_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual_production.attendanceselect', verbose_name='勤怠選択肢'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'attendance_date'], name='actual_prod_employe_ab3af3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_date'], name='actual_prod_attenda_214bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'attendance_date')},
        ),
        migrations.AddIndex(
            model_name='attendanceproductionmapping',
            index=models.Index(fields=['attendance_select', 'active'], name='actual_prod_attenda_48f16a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceproductionmapping',
            index=models.Index(fields=['actual_production_item', 'active'], name='actual_prod_actual__4edd05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceproductionmapping',
            unique_together={('attendance_select', 'actual_production_item')},
        ),
    ]
