# Generated by Django 5.2.6 on 2025-11-10 15:35

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ライン名')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'ライン',
                'verbose_name_plural': 'ライン',
                'ordering': ['-active', 'name'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MachiningMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='設備名')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '加工機',
                'verbose_name_plural': '加工機',
                'ordering': ['-active', 'line__name', 'name'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MachiningToolNo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ツールNo')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'ツールNo',
                'verbose_name_plural': 'ツールNo',
                'ordering': ['-active', 'line__name', 'machine__name', 'name'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MachiningLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.line')),
            ],
            options={
                'verbose_name': '加工ライン',
                'verbose_name_plural': '加工ライン',
            },
            bases=('manufacturing.line',),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['name'], name='manufacturi_name_ea0c45_idx'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['active', 'name'], name='manufacturi_active_d4be25_idx'),
        ),
        migrations.AddField(
            model_name='machiningtoolno',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_nos', to='manufacturing.machiningmachine', verbose_name='加工機'),
        ),
        migrations.AddField(
            model_name='machiningtoolno',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_nos', to='manufacturing.machiningline', verbose_name='ライン'),
        ),
        migrations.AddField(
            model_name='machiningmachine',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='manufacturing.machiningline', verbose_name='ライン'),
        ),
        migrations.AddIndex(
            model_name='machiningtoolno',
            index=models.Index(fields=['name'], name='manufacturi_name_6bd28b_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningtoolno',
            index=models.Index(fields=['active', 'name'], name='manufacturi_active_0657f9_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningtoolno',
            index=models.Index(fields=['machine', 'active'], name='manufacturi_machine_06e082_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningtoolno',
            index=models.Index(fields=['line', 'active'], name='manufacturi_line_id_553605_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmachine',
            index=models.Index(fields=['name'], name='manufacturi_name_01509c_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmachine',
            index=models.Index(fields=['active', 'name'], name='manufacturi_active_3a07d5_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmachine',
            index=models.Index(fields=['line', 'active'], name='manufacturi_line_id_ecad6c_idx'),
        ),
    ]
