# Generated by Django 5.2.6 on 2025-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='occupancy_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='稼働率'),
        ),
    ]
