# Generated by Django 5.2.6 on 2025-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_line_occupancy_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='yield_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='良品率'),
        ),
    ]
