# Generated by Django 5.2.6 on 2025-11-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_line_yield_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.line')),
            ],
            options={
                'verbose_name': '組付ライン',
                'verbose_name_plural': '組付ライン',
            },
            bases=('manufacturing.line',),
        ),
        migrations.CreateModel(
            name='CastingLineLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.line')),
            ],
            options={
                'verbose_name': '鋳造ライン',
                'verbose_name_plural': '鋳造ライン',
            },
            bases=('manufacturing.line',),
        ),
    ]
