# Generated by Django 5.2.6 on 2025-11-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_assemblyline_castinglineline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CastingLineLine',
            new_name='CastingLine',
        ),
    ]
