# Generated by Django 5.2.6 on 2025-11-10 17:20

import daihatsu.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_rename_castinglineline_castingline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='設備名')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('last_updated_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'ordering': ['-active', 'line__name', 'name'],
            },
            bases=(daihatsu.models.MasterMethodMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='machiningmachine',
            options={'verbose_name': '加工機', 'verbose_name_plural': '加工機'},
        ),
        migrations.RemoveIndex(
            model_name='machiningmachine',
            name='manufacturi_name_01509c_idx',
        ),
        migrations.RemoveIndex(
            model_name='machiningmachine',
            name='manufacturi_active_3a07d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='machiningmachine',
            name='manufacturi_line_id_ecad6c_idx',
        ),
        migrations.RemoveField(
            model_name='machiningmachine',
            name='active',
        ),
        migrations.RemoveField(
            model_name='machiningmachine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='machiningmachine',
            name='last_updated_user',
        ),
        migrations.RemoveField(
            model_name='machiningmachine',
            name='line',
        ),
        migrations.RemoveField(
            model_name='machiningmachine',
            name='name',
        ),
        migrations.CreateModel(
            name='CastingMachine',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.machine')),
            ],
            options={
                'verbose_name': '鋳造機',
                'verbose_name_plural': '鋳造機',
            },
            bases=('manufacturing.machine',),
        ),
        migrations.AddField(
            model_name='machine',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='manufacturing.line', verbose_name='ライン'),
        ),
        migrations.AddField(
            model_name='machiningmachine',
            name='machine_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.machine'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['name'], name='manufacturi_name_c0da79_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['active', 'name'], name='manufacturi_active_f3aaba_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['line', 'active'], name='manufacturi_line_id_23ea07_idx'),
        ),
    ]
