# Generated by Django 5.2.6 on 2025-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_machine_alter_machiningmachine_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='yield_rate',
        ),
        migrations.AddField(
            model_name='assemblyline',
            name='tact',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='タクト'),
        ),
        migrations.AddField(
            model_name='assemblyline',
            name='yield_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='良品率'),
        ),
        migrations.AddField(
            model_name='machiningline',
            name='tact',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='タクト'),
        ),
        migrations.AddField(
            model_name='machiningline',
            name='yield_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='良品率'),
        ),
    ]
