# Generated by Django 5.2.6 on 2025-11-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_remove_line_yield_rate_assemblyline_tact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machiningline',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machining_lines', to='manufacturing.assemblyline', verbose_name='組付ライン'),
        ),
    ]
