# Generated by Django 5.2.6 on 2025-11-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_machiningline_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyline',
            name='yield_rate',
        ),
    ]
