# Generated by Django 5.2.6 on 2025-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_remove_assemblyline_yield_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['-active', 'order', 'name'], 'verbose_name': 'ライン', 'verbose_name_plural': 'ライン'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-active', 'line__order', 'order', 'name'], 'verbose_name': '設備', 'verbose_name_plural': '設備'},
        ),
        migrations.AddField(
            model_name='line',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='machine',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示順'),
        ),
    ]
