# Generated by Django 5.2.6 on 2025-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_alter_line_options_alter_machine_options_line_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingline',
            name='changeover_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='段取時間'),
        ),
    ]
