# Generated by Django 5.2.6 on 2025-12-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_castingline_changeover_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTLine',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.line')),
                ('changeover_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='段取時間')),
            ],
            options={
                'verbose_name': 'CVTライン',
                'verbose_name_plural': 'CVTライン',
            },
            bases=('manufacturing.line',),
        ),
        migrations.CreateModel(
            name='CVTMachine',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.machine')),
            ],
            options={
                'verbose_name': '鋳造機(CVT)',
                'verbose_name_plural': '鋳造機(CVT)',
            },
            bases=('manufacturing.machine',),
        ),
    ]
