# Generated by Django 5.2.6 on 2025-11-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_room_time', models.TimeField(blank=True, null=True, verbose_name='入室時間')),
                ('annual_leave', models.BooleanField(default=False, verbose_name='年休')),
                ('morning_annual_leave', models.BooleanField(default=False, verbose_name='午前年休')),
                ('afternoon_annual_leave', models.BooleanField(default=False, verbose_name='午後年休')),
                ('business_trip', models.BooleanField(default=False, verbose_name='出張')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_room.employee', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '入室管理',
                'verbose_name_plural': '入室管理',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='タイトル')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='場所')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_room.employee', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
            },
        ),
    ]
